title: Distinguished Paper Series

logo: /assets/img/dist-paper-series-rect.png
title-below-logo: false

description:
show_downloads: false
theme: jekyll-theme-minimal

include:
  - pages

colors:
  theme: 008000
  theme-light: 4CBB17
  theme-dark: 002000
